partcad/partcad

README.md

This saves visitors that do not already now these projects, from searching for them manually.

README: Adds links to mentioned projects and formats

---

requirements.txt

Added dependency on pycairo in an attempt to simplify installation on Windows

Added dependency on pycairo

---

partcad-cli/src/partcad_cli/cli.py
partcad-cli/src/partcad_cli/cli_add.py
partcad/src/partcad/project.py

Add command line interface to add parts and assemblies

---

examples/produce_part_step/partcad.yaml
partcad-cli/src/partcad_cli/cli_list.py
partcad/src/partcad/part.py
partcad/src/partcad/part_factory.py
partcad/src/partcad/part_factory_3mf.py
partcad/src/partcad/part_factory_alias.py
partcad/src/partcad/part_factory_file.py
partcad/src/partcad/part_factory_python.py
partcad/src/partcad/part_factory_scad.py
partcad/src/partcad/part_factory_step.py
partcad/src/partcad/part_factory_stl.py
partcad/src/partcad/project.py
partcad/tests/unit/test_part.py

Added multiple ways to define aliases. In all cases they can be distinguished from regular parts (for UI/UX).

Improved alias support

---

partcad-cli/src/partcad_cli/cli.py
partcad-cli/src/partcad_cli/cli_status.py
partcad/src/partcad/__init__.py
partcad/src/partcad/project_factory_git.py
partcad/src/partcad/project_factory_tar.py
partcad/src/partcad/runtime.py
partcad/src/partcad/user_config.py

Added a configuration option to relocate the internal data storage.
Added "pc status" to show the state of the internal data storage.

Added "pc status"

---

examples/partcad.yaml
examples/produce_part_extrude/partcad.yaml
partcad/src/partcad/context.py
partcad/src/partcad/part_factory_enrich.py
partcad/src/partcad/project.py
partcad/src/partcad/shape.py
partcad/src/partcad/utils.py

…  Also fix multiple race conditions that become more problematic when relative paths are used

Enable relative package path

---

.github/workflows/python-test.yml
README.md
partcad/src/partcad/logging.py
partcad/src/partcad/part_factory_build123d.py
partcad/src/partcad/part_factory_cadquery.py
partcad/src/partcad/part_factory_scad.py
partcad/src/partcad/part_factory_step.py
partcad/src/partcad/project_factory_git.py
partcad/src/partcad/provider_factory_python.py
partcad/src/partcad/runtime_python.py
partcad/src/partcad/runtime_python_conda.py
partcad/src/partcad/runtime_python_none.py
partcad/src/partcad/shape.py
partcad/src/partcad/sketch_factory_build123d.py
partcad/src/partcad/sketch_factory_cadquery.py

This pull request includes several changes to improve compatibility and functionality across different environments, particularly focusing on Windows compatibility and enhancing the Python runtime setup. The most important changes include adjustments to dependency versions, modifications to subprocess handling, and improvements to virtual environment management.
* Updated `typing_extensions` dependency to a fixed version `4.12.2` across multiple files to address compatibility issues on Windows. (`partcad/src/partcad/part_factory_build123d.py`, `partcad/src/partcad/part_factory_cadquery.py`, `partcad/src/partcad/provider_factory_python.py`, `partcad/src/partcad/runtime_python.py`, `partcad/src/partcad/sketch_factory_build123d.py`, `partcad/src/partcad/sketch_factory_cadquery.py`) …

Fix test on windows

---

.devcontainer/.pre-commit-config.yaml
.devcontainer/behave_hook.sh
.devcontainer/devcontainer.json
.github/workflows/dev-container.yml
behave.ini
features/add/dependency.feature
features/add/part.feature
features/add/sketch.feature
features/environment.py
features/info.feature
features/init.feature
features/list/assemblies.feature
features/list/interfaces.feature
features/list/sketches.feature
features/status.feature
features/steps/partcad-cli/commands/add/assembly.py
features/steps/partcad-cli/commands/status.py
features/test.feature
partcad-cli/src/partcad_cli/click/commands/init.py

- Add pre-commit hook to run behave tests in parallel using behavex.
- Update .github/workflows/dev-container.yml to include behave in skipped jobs.
- Modify behave.ini for allure reporting.
- Fix broken behave tests

feat(devcontainer): add behave hook for parallel testing

---

.github/workflows/test.yml
dev-tools/coverage.rc

fix(CI): Coverage reports are failing in CI

---

partcad-cli/src/partcad_cli/click/command.py
partcad/src/partcad/context.py
partcad/src/partcad/project_factory_git.py
partcad/src/partcad/user_config.py
partcad/tests/unit/test_context.py

- Added `--offline` option to partcad-cli for offline operation.
- Implemented connectivity check in partcad context.
- Cached connectivity status for better performance.
- Updated tests to include offline mode scenarios.

feat(partcad): Add offline mode for git ops

---

.github/workflows/dev-container.yml
.github/workflows/test.yml
dev-tools/coverage.rc
features/install.feature
features/pc.feature
features/steps/partcad-cli/commands/list/packages.py

fix(CI): "behave" fails in GitHub Windows runners

---

.devcontainer/devcontainer.json
.github/actions/setup-all/action.yml
.github/actions/setup-build/action.yml
.github/actions/setup-cadquery/action.yml
.github/actions/setup-devcontainer/action.yml
.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/test-dev.yml
.github/workflows/test.yml
partcad/LICENSE
partcad/pyproject.toml
poetry.lock
pyproject.toml

Fixing workflows

---

.github/workflows/test.yml
partcad-cli/src/partcad_cli/click/commands/test.py
partcad/src/partcad/project.py
partcad/src/partcad/runtime_python.py
partcad/src/partcad/shape.py
partcad/src/partcad/test/all.py
partcad/src/partcad/test/test.py

feat(dev): test commit

---

docs/source/troubleshooting.rst
features/healthcheck.feature
features/steps/partcad-cli/commands/healthcheck/common.py
partcad-cli/src/partcad_cli/click/commands/healthcheck.py
partcad/src/partcad/healthcheck/healthcheck.py

- Add healthcheck command to partcad-cli
- Add healthcheck module to partcad
- Add HealthCheckTest interface to partcad.healthcheck

feat(partcad-cli): add pc healthcheck command

---

features/healthcheck.feature
features/steps/partcad-cli/commands/healthcheck/common.py
features/steps/partcad-cli/commands/healthcheck/windows_registry.py
partcad-cli/src/partcad_cli/click/commands/healthcheck.py
partcad/src/partcad/healthcheck/healthcheck.py
partcad/src/partcad/healthcheck/python_version.py
partcad/src/partcad/healthcheck/windows_registry.py

- Add healthcheck test for LongPathsEnabled registry key
- Add healthcheck test for NoDefaultCurrentDirectoryInExePath registry key

feat(healthcheck): add windows registry healthcheck

---

tools/containers/kicad/Dockerfile

Updated curl version to fix the docker build

---

docs/source/troubleshooting.rst
features/healthcheck.feature
features/steps/partcad-cli/commands/healthcheck/common.py
partcad-cli/src/partcad_cli/click/commands/healthcheck.py
partcad/src/partcad/healthcheck/healthcheck.py
partcad/src/partcad/healthcheck/python_version.py
partcad/src/partcad/healthcheck/windows_registry.py

- Added filtering options to health check command `pc healthcheck --filter <filter-tag>`.
- Added dry-run option to health check command `pc healthcheck --dry-run`

feat(healthcheck): update cli options `pc healthcheck` command

---

partcad/tests/unit/test_convert_part.py

Reproducible order of conversion test cases to fix pre-commit checks

---

partcad/src/partcad/assembly.py
partcad/src/partcad/cache_hash.py

Fixed assembly with multiple parts of the same kind

---

docs/source/tutorial.rst
docs/source/use_cases.rst
examples/feature_export/partcad.yaml
features/export.feature
features/render.feature
partcad-cli/src/partcad_cli/click/commands/convert.py
partcad-cli/src/partcad_cli/click/commands/export.py
partcad/src/partcad/actions/part/convert.py
partcad/src/partcad/project.py
partcad/src/partcad/shape.py
partcad/src/partcad/wrappers/wrapper_render_iges.py
partcad/tests/unit/test_convert_part.py

feat: Add support for IGES parts

---

docs/source/design.rst
docs/source/features.rst
partcad-cli/src/partcad_cli/click/command.py
partcad-cli/src/partcad_cli/click/commands/info.py
partcad/src/partcad/config.py
partcad/src/partcad/interface.py
partcad/src/partcad/part_config.py
partcad/src/partcad/part_factory_enrich.py
partcad/src/partcad/project.py
partcad/src/partcad/project_config.py
partcad/src/partcad/provider_config.py
partcad/src/partcad/provider_factory_enrich.py
partcad/src/partcad/provider_factory_python.py
partcad/src/partcad/sketch_config.py
partcad/src/partcad/sketch_factory_enrich.py
partcad/src/partcad/user_config.py
partcad/tests/unit/test_part_params.py
partcad/tests/unit/test_provider.py

feat: update user configurations
